### ISSUE TITLE
[WITH FIX] Cannot download, module :public_key is not available erlang

### ISSUE THREAD

**Issue by Rem0ld** [mhanberg/advent-of-code-elixir-starter#14]
Error with mix d01.p1.
With some research I found this thread giving the solution

[https://github.com/elixir-lang/elixir/issues/12681#issuecomment-1598312912](https://github.com/elixir-lang/elixir/issues/12681#issuecomment-1598312912)

Adding this to mix deps fix the issue
 ```{:ssl_verify_fun, "~> 1.1.7", manager: :rebar3, override: true}```

Just in case someone else has the problem 🙂
Thanks for the template!

**Comment by mhanberg** [comment]
PR is welcome!
