### ISSUE TITLE
`AdventOfCode.Input.get!(2)` and subsequents fail

### ISSUE THREAD

**Issue by palozano** [mhanberg/advent-of-code-elixir-starter#16]
I cannot get the input from any other day that is not the first day. Am I doing something wrong?

Error:
```
** (MatchError) no match of right hand side value: {:error, {:headers_error, :invalid_field}}
    (advent_of_code 0.1.0) lib/advent_of_code/input.ex:53: AdventOfCode.Input.download!/2
    iex:2: (file)
```

**Comment by mhanberg** [comment]
Try applying this diff

```diff
diff --git a/mix.exs b/mix.exs
index 4116f66..017ffd1 100644
--- a/mix.exs
+++ b/mix.exs
@@ -14,7 +14,7 @@ defmodule AdventOfCode.MixProject do
   # Run "mix help compile.app" to learn about applications.
   def application do
     [
-      extra_applications: [:logger, :inets]
+      extra_applications: [:logger, :inets, :public_key, :ssl]
     ]
   end
 
```

**Comment by palozano** [comment]
Erlang/OTP 27, Elixir 1.17.3.

No luck with that diff. Outside IEx, for `mix d02.p1` the error shows:
```
** (MatchError) no match of right hand side value: {:error, {:headers_error, :invalid_field}}
    (advent_of_code 0.1.0) lib/advent_of_code/input.ex:53: AdventOfCode.Input.download!/2
    (advent_of_code 0.1.0) lib/mix/tasks/d02.p1.ex:8: Mix.Tasks.D02.P1.run/1
    (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /opt/homebrew/bin/mix:2: (file)
```

**Comment by mhanberg** [comment]
Have you set your session token?

**Comment by palozano** [comment]
Yes. And it works for day 1, but for 2 and onwards it fails

**Comment by mhanberg** [comment]
I freshly cloned the starter template and its all working for me

iex
![CleanShot 2024-12-04 at 09 39 21@2x](https://github.com/user-attachments/assets/23eb0fdd-494b-439c-9140-cdad6a4dc419)

mix task
![CleanShot 2024-12-04 at 09 40 53@2x](https://github.com/user-attachments/assets/62a02009-0b45-47eb-81c9-57cf57677f3a)

I would double check that your AdventOfCode.Input module is identical to what is on the main branch right now

**Comment by palozano** [comment]
Recloned again the repo and now it works. I cannot tell you what I did wrong but, if I find out, I will post it here. Thanks a lot!
