### ISSUE TITLE
Remove warnings for deprecated Mix.Config

### ISSUE THREAD

**Issue by vaeng** [mhanberg/advent-of-code-elixir-starter#9]
Hi there,

I get:
```elixir
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:1

warning: use Mix.Config is deprecated. Use the Config module instead
  config/secrets.exs:1
```

Is it possible to alter the structure so that those two disappear? I don't know enough about the config module to do it myself.

**Comment by mhanberg** [comment]
I believe all you nee to do is replace `use Mix.Config` with `import Config`

**Comment by vaeng** [comment]
That's true, I removed the Mix part, but I did not see the change from use to import.
